name: Deploy to Azure
on:
  push:
    branches:
      - main
env:
  AZURE_WEBAPP_NAME: Pokemon-Trading-App
  AZURE_WEBAPP_PACKAGE_PATH: './pokeApp.UI/poke-app/dist/poke-app'
  NODE_VERSION: '16.13.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        
    - name: Install dependencies
      run: |
        cd pokeApp.UI/poke-app/
        npm install
      
    - name: Build
      run: |
        cd pokeApp.UI/poke-app/
        npm run build --if-present
        
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FOR_UI }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
